[workspace]
members = ["game-station"]
resolver = "2"

[workspace.dependencies]
async-graphql = { version = "7.0.17", default-features = false }
futures = "0.3"
linera-sdk = "0.15.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
